[build]
base = "apps/web"
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[env.production]
NEXT_PUBLIC_API_BASE_URL = "https://noyyal-api.onrender.com"

[env.development]
NEXT_PUBLIC_API_BASE_URL = "http://localhost:8000"
